### ISSUE TITLE
Azure Devops Pipeline error - 'Unknown argument --async'

### ISSUE THREAD

**Issue by IeuanWalker** [microsoft/appcenter#1852]
Adding the command `--async` works fine locally allowing me to add `--async true` to stop listening for results once all the files have been passed to appcenter.

Adding the same command to the Azure pipeline i get this error - `Unknown argument --async` 
```
  - task: AppCenterTest@1
          inputs:
            appFile: '$(Build.ArtifactStagingDirectory)\AndroidBuild\App.Android.apk'
            artifactsDirectory: '$(System.ArtifactsDirectory)\AppCenterTest'
            frameworkOption: 'uitest'
            uiTestBuildDirectory: '$(Build.ArtifactStagingDirectory)\TestStuff'
            uiTestToolsDirectory: '$(Build.ArtifactStagingDirectory)\TestStuff'
            prepareOptions: '--include-category $(TestInclude) --exclude-category $(TestExclude) --async $(TestAsync)'
            credentialsOption: 'serviceEndpoint'
            serverEndpoint: '*****'
            appSlug: '*******'
            devices: '$(Devices)'
            series: '$(TestSeries)'
            localeOption: 'en_GB'
```

This is needed as when all the UI tests run the duration is longer than 60m and the hosted pipeline timesout after 60m which shows it as a failure, it also means and entire pipeline is busy for 60m for no reason.
