### ISSUE TITLE
AppCenter pipelines PDB file upload

### ISSUE THREAD

**Issue by nabeelio** [microsoft/appcenter#2256]
Hello, I was talking to support and they suggested I make this issue... the docs here suggest that you can upload a PDB file for WPF apps: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=azure-devops

However, in the YAML that's generated by a release task in Azure Pipelines gives this:

```yaml
steps:
- task: AppCenterDistribute@3
  displayName: 'Deploy to Visual Studio App Center'
  inputs:
    serverEndpoint: 'visual studio app center'
    appSlug: 'my/app/slug
    appFile: '$(System.DefaultWorkingDirectory)/dotnet-build/release/release.zip'
    buildVersion: '$(Build.BuildNumber)'
    symbolsOption: UWP
    appxsymPath: '$(System.DefaultWorkingDirectory)/dotnet-build/pdb/acars.pdb'
    releaseNotesOption: file
    releaseNotesFile: '$(System.DefaultWorkingDirectory)/dotnet-build/release/CHANGELOG.md'
    isMandatory: true
    distributionGroupId: 'e4868684-143d-4516-85a3-3b324c5a3064'
    isSilent: false
```

I'm just confused as to why the generated YAML is different from the docs. Anyway, I'd like to be able to upload the PDB files for my WPF app. `WPF` isn't available as an option in the dropdown, the closest is `UWP`.

To be honest, I'm not sure if this will accomplish what I want - which is just seeing which lines exceptions occurred on (particularly null references) from release builds.

Thanks!
